import Categories from "./Categories.jsx";
import News from "./News.jsx";
import CourseEducation from "./CourseEducation.jsx";
import HeroSectionSvg from "./HeroSectionSvg.jsx";
import HeroSection from "./HeroSection.jsx";
import NewsCard from "./NewsCard.jsx";
import OurTeachers from "./OurTeachers.jsx";
import Services from "./Services.jsx";
import Suggestions from "./Suggestions.jsx";
import Course from "./course/Course.jsx";
import CourseBody from "./course/CourseBody.jsx";
import CourseHeader from "./course/CourseHeader.jsx";
export {Categories , News , CourseEducation , HeroSection,HeroSectionSvg,NewsCard,OurTeachers,Services,Suggestions,Course,CourseHeader,CourseBody};